import React from "react";
import Head from "next/head";
import styles from "@styles/Home.module.css";

interface HomeProps {
  data: string;
}

export default function Home(props: HomeProps) {
  const { data } = props;
  return (
    <>
      <Head>
        <title>C Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Hello there!</h1>
        <span>Output: {data}</span>
      </main>
    </>
  );
}

export async function getServerSideProps(): Promise<{ props: HomeProps }> {
  const SSProps = {
    props: {
      data: "<data to fetch>",
    },
  };

  const response = await fetch("http://localhost:3000/");

  if (response.ok) {
    const data = await response.json();
    SSProps.props.data = data.text;
  } else {
    SSProps.props.data = `Error on data fetching. Status Code: ${response.status}`;
  }

  return SSProps;
}
